//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar ao carrinho.
        /// </summary>
        public static string AdicionarAoCarrinho {
            get {
                return ResourceManager.GetString("AdicionarAoCarrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string Atualizar {
            get {
                return ResourceManager.GetString("Atualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrinho.
        /// </summary>
        public static string Carrinho {
            get {
                return ResourceManager.GetString("Carrinho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edição de {0}.
        /// </summary>
        public static string EdicaoDeX {
            get {
                return ResourceManager.GetString("EdicaoDeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de {0}.
        /// </summary>
        public static string ExclusaoDeX {
            get {
                return ResourceManager.GetString("ExclusaoDeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir {0}.
        /// </summary>
        public static string IncluirX {
            get {
                return ResourceManager.GetString("IncluirX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusão de {0}.
        /// </summary>
        public static string InclusaoDeX {
            get {
                return ResourceManager.GetString("InclusaoDeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de {0}.
        /// </summary>
        public static string ListaDeX {
            get {
                return ResourceManager.GetString("ListaDeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pague um Leve dois.
        /// </summary>
        public static string PagueUmLeveDois {
            get {
                return ResourceManager.GetString("PagueUmLeveDois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço.
        /// </summary>
        public static string Preco {
            get {
                return ResourceManager.GetString("Preco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        public static string Produto {
            get {
                return ResourceManager.GetString("Produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        public static string Produtos {
            get {
                return ResourceManager.GetString("Produtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoção.
        /// </summary>
        public static string Promocao {
            get {
                return ResourceManager.GetString("Promocao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Quantidade {
            get {
                return ResourceManager.GetString("Quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remover {
            get {
                return ResourceManager.GetString("Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem promoção.
        /// </summary>
        public static string SemPromocao {
            get {
                return ResourceManager.GetString("SemPromocao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Três por 10 Reais.
        /// </summary>
        public static string TresPorDezReais {
            get {
                return ResourceManager.GetString("TresPorDezReais", resourceCulture);
            }
        }
    }
}
